-- MySQL Script generated by MySQL Workbench
-- Fri May 26 17:43:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema telovendopedidos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema telovendopedidos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `telovendopedidos` DEFAULT CHARACTER SET utf8 ;
USE `telovendopedidos` ;

-- -----------------------------------------------------
-- Table `telovendopedidos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telovendopedidos`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `direccion_envio` VARCHAR(45) NOT NULL,
  `saldo` INT NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telovendopedidos`.`fabrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telovendopedidos`.`fabrica` (
  `idfabrica` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(45) NOT NULL,
  `stock` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idfabrica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telovendopedidos`.`fabrica_alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telovendopedidos`.`fabrica_alternativa` (
  `idfabrica_alternativa` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(45) NOT NULL,
  `stock` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idfabrica_alternativa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telovendopedidos`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telovendopedidos`.`articulo` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT,
  `idfabrica` INT NOT NULL,
  `existencias` INT UNSIGNED NOT NULL,
  `descripcion` TEXT NULL,
  `idfabrica_alternativa` INT NULL,
  PRIMARY KEY (`idarticulo`),
  INDEX `articulo_idfabrica_fk_idx` (`idfabrica` ASC) VISIBLE,
  INDEX `articulo_idfabrica_alternativa_fk_idx` (`idfabrica_alternativa` ASC) VISIBLE,
  CONSTRAINT `articulo_idfabrica_fk`
    FOREIGN KEY (`idfabrica`)
    REFERENCES `telovendopedidos`.`fabrica` (`idfabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_idfabrica_alternativa_fk`
    FOREIGN KEY (`idfabrica_alternativa`)
    REFERENCES `telovendopedidos`.`fabrica_alternativa` (`idfabrica_alternativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telovendopedidos`.`cabecera_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telovendopedidos`.`cabecera_pedido` (
  `idcabecera_pedido` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `direccion_envio` VARCHAR(45) NOT NULL,
  `fecha_pedido` DATETIME NOT NULL,
  PRIMARY KEY (`idcabecera_pedido`),
  INDEX `cabecera_pedido_idcliente_fk_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `cabecera_pedido_idcliente_fk`
    FOREIGN KEY (`idcliente`)
    REFERENCES `telovendopedidos`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telovendopedidos`.`cuerpo_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telovendopedidos`.`cuerpo_pedido` (
  `idcuerpo_pedido` INT NOT NULL AUTO_INCREMENT,
  `idarticulo` INT NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `idcabecera_pedido` INT NOT NULL,
  PRIMARY KEY (`idcuerpo_pedido`),
  INDEX `cuerpo_pedido_idcabecera_pedido_fk_idx` (`idcabecera_pedido` ASC) VISIBLE,
  INDEX `cuerpo_pedido_idarticulo_fk_idx` (`idarticulo` ASC) VISIBLE,
  UNIQUE INDEX `idarticulo_UNIQUE` (`idarticulo` ASC) VISIBLE,
  CONSTRAINT `cuerpo_pedido_idcabecera_pedido_fk`
    FOREIGN KEY (`idcabecera_pedido`)
    REFERENCES `telovendopedidos`.`cabecera_pedido` (`idcabecera_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cuerpo_pedido_idarticulo_fk`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `telovendopedidos`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
